services:
  api:
    build: api/
    restart: unless-stopped
  docs:
    build: docs/
    restart: unless-stopped
  client:
    build: client/
    restart: unless-stopped
  gateway:
    build: gateway/
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - api
      - docs
      - client
